name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  make-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.0
          cache: 'yarn'
      - name: Install Node Modules
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Make
        run: yarn run make
      - run: ls out/make/**/*
      - name: Rename File
        run: mv out/make/Codey*.dmg "out/make/Codey (macOS).dmg"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: macos-app
          path: "out/make/Codey (macOS).dmg"
  make-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.0
          cache: 'yarn'
      - name: Install Node Modules
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Make
        run: yarn run make
      - run: ls out/make/**/*
      - name: Rename Files
        run: |
          mv out/make/deb/x64/codey*.deb "out/make/deb/x64/Codey (Debian).deb"
          mv out/make/rpm/x64/Codey*.rpm "out/make/rpm/x64/Codey (RPM).rpm"
      - name: Upload Debian Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: deb-app
          path: "out/make/deb/x64/Codey (Debian).deb"
      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: rpm-app
          path: "out/make/rpm/x64/Codey (RPM).rpm"
  make-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.0
          cache: 'yarn'
      - name: Install Node Modules
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Make
        run: yarn run make
      - name: Rename File
        run: move out/make/squirrel.windows/x64/Codey*.exe "out/make/squirrel.windows/x64/Codey (Windows).exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-app
          path: "out/make/squirrel.windows/x64/Codey (Windows).exe"
  build_release:
    runs-on: ubuntu-latest
    needs: [make-macos, make-linux, make-windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create dist directory
        run: mkdir dist
      - name: Download macOS App
        uses: actions/download-artifact@v2.1.0
        with:
          name: macos-app
          path: dist
      - name: Download DEB App
        uses: actions/download-artifact@v2.1.0
        with:
          name: deb-app
          path: dist
      - name: Download RPM App
        uses: actions/download-artifact@v2.1.0
        with:
          name: rpm-app
          path: dist
      - name: Download Windows App
        uses: actions/download-artifact@v2.1.0
        with:
          name: windows-app
          path: dist
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            dist
            LICENSE
